### ISSUE TITLE
What is the difference between this repo and ros2 /rosidl/rosidl_adapter?

### ISSUE THREAD

**Issue by weithegreat** [ros2/rosidl_dds#57]
Hey was wondering what is the difference between this repo and ros2 /rosidl/rosidl_adapter? They seem to have very similar functionality

**Comment by clalancette** [comment]
@hidmic can probably give an overview here.

**Comment by hidmic** [comment]
@weigewansui both `rosidl_adapter` and `rosidl_generator_dds_idl` packages enable some form of interface definition "translation", but on different formats. `rosidl_adapter` takes `.msg`, `.srv`, and `.action` files and outputs `.idl` files, whereas `rosidl_generator_dds_idl` takes `.idl` files and outputs another flavor of `.idl` files, suitable for some external code generators. The split in different packages is purely due to code organization.

As a side note, I don't know if you're familiar with https://answers.ros.org/ but we typically encourage everyone to make questions there instead of opening issues. That way, you get prompt replies from the broader community and other people may get to see the exchange in the future. Please, consider making your next question over there :)
